### ISSUE TITLE
Format of .npy files

### ISSUE THREAD

**Issue by cherif54** [seorim0/DCCRN-with-various-loss-functions#4]
Hi, the datasets in the code are loaded with .npy files. What type of information do they contain? Is it just the path to each individual file?

**Comment by seorim0** [comment]
Hi~ It is a bundle of clean speeches used as target (label) and noisy speeches used as input. Not the path, but the data itself.
So, the shape of .npy files is `[total data number, 2 (input & target), wav length (chunk size)]`

You can also load and use only the path like the code below.
https://github.com/seorim0/NUNet-TLS/blob/main/dataloader.py

**Comment by cherif54** [comment]
Thanks. I'm running through this error "No module names estimate" in train.py. I think that file is missing from the repo. 
![image](https://user-images.githubusercontent.com/77592579/172696433-8679d02b-6b55-4fb3-a3c0-10c6163a3e01.png)

**Comment by cherif54** [comment]
I resolved this with the tools.py. However, there is a "write_on_tensorboard" module that is missing.

**Comment by seorim0** [comment]
I uploaded it! Sorry, I forgot. 
The output is written to the tensorboard during training, and you can edit `write_on_tensorboard.py` if you have additional outputs you would like to add. Or you can delete that part.
