### ISSUE TITLE
Missing function

### ISSUE THREAD

**Issue by cherif54** [seorim0/DCCRN-with-various-loss-functions#5]
Hi, 
the log_data_we_want function is missing in write_on_tensorboard.py

**Comment by seorim0** [comment]
Hi!
Thanks for your interest in my repo.
I changed 'train.py' and 'write_on_tensorboard.py' about a month ago.
You can use the 'save_samples_we_want' function instead of the 'log_data_we_want function'.

**Comment by cherif54** [comment]
Thanks for the reply. Also noticed that there is a missing module for the pesq and stoi. The line for import is below

"from estimate import run_pesq_waveforms_array, cal_stoi"

**Comment by seorim0** [comment]
I added the code below. (changed 'train.py', 'tools_for_model.py')
```
def cal_pesq(dirty_wavs, clean_wavs):
    pesq_scores = []
    for i in range(len(dirty_wavs)):
        pesq_score = pesq(cfg.FS, clean_wavs[i], dirty_wavs[i], "wb")
        pesq_scores.append(pesq_score)
    return pesq_scores


def cal_stoi(dirty_wavs, clean_wavs):
    stoi_scores = []
    for i in range(len(dirty_wavs)):
        stoi_score = stoi(clean_wavs[i], dirty_wavs[i], cfg.FS, extended=False)
        stoi_scores.append(stoi_score)
    return stoi_scores
```

Have a good day :)
