### ISSUE TITLE
Some questions about perceptual_transform func？ 

### ISSUE THREAD

**Issue by zuowanbushiwo** [seorim0/DCCRN-with-various-loss-functions#7]
Hi @seorim0 
    https://github.com/seorim0/DCCRN-with-various-loss-functions/blob/main/tools_for_loss.py#L206  
   Why use `view` here, should not be `transpose`？
    input `x` is `(...,  freq,time) ` and  we need   `(..., n_mels, time) ` output， so   ` (..., time, freq)` dot `(freq, n_mels) -> (..., n_mels, time)`？
    thanks！

**Comment by seorim0** [comment]
Hi. What you understand is correct. There is no particular reason to use a `view`.
