### ISSUE TITLE
ModuleNotFoundError: No module named 'run'

### ISSUE THREAD

**Issue by lixinlun** [seorim0/DCCRN-with-various-loss-functions#9]
Hi, I am new to deep learning.

In the trainer.py, line 17:
from run import model_train, model_validate, model_test

I dont find the run.py in the project.
Are those 3 models in train.py?

Thank you!谢谢！

**Comment by seorim0** [comment]
Hi!
Yes, you are right.
It's a typo. I edited.

Thank you for your interest in my project.
If you have any additional questions, feel free to ask!

**Comment by lixinlun** [comment]
Okok!
Your project should help me a lot!
Thank you for your timely response Thanks again!~
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
